;CHECKING LDRB KA OUTPUT , IT TAKED THE LDB
	AREA RESET,DATA,READONLY 
	EXPORT __Vectors
__Vectors
	DCD 0x10001000;
	DCD Reset_Handler;
	ALIGN 
	AREA myarea,CODE , READONLY 
	EXPORT Reset_Handler
Reset_Handler 
	LDR R0,=SRC1
	LDRH R1,[R0]
	STR R2,[R1]
	LDR R5,=SRC2
	LDR R6,[R5]
	STRB R6,[R7]
STOP
	B STOP 
SRC1 DCD 0XF51DC32A
SRC2 DCD 0XFF88AA99
	AREA MYDATA,DATA,READWRITE 
;RES DCD 0,0,0,0,0
	END