;SUM OF N NATURAL NUMBERS 
	AREA RESET,DATA,READONLY 
	EXPORT __Vectors
__Vectors
	DCD 0X10001000;
	DCD Reset_Handler ;
	ALIGN 
	AREA mycode,CODE,READONLY 
	ENTRY 
	EXPORT Reset_Handler 
Reset_Handler 
	LDR R0,=N
	LDR R1,=RES 
	LDR R0,[R0]
	MLA R2,R0,R0,R0
	LSR R2,#1
	STR R2,[R1]
STOP 
	B STOP 
N DCD 0X5 
	AREA MYDATA ,DATA ,READWRITE 
RES DCD 0 
	END
	; SUM OF FIRST N NATURAL NUMBERS 
	