;lcm 
	AREA RESET,DATA,READONLY 
	EXPORT __Vectors
__Vectors
	DCD 0X1000100;
	DCD Reset_Handler 
	ALIGN 
	AREA mycode,CODE,READONLY 
	ENTRY 
	EXPORT Reset_Handler 
Reset_Handler 
	LDR R0,=SRC1
	LDR R1,=SRC2
	LDR R2,=RES
	LDR R0,[R0]
	LDR R1,[R1]
	MOV R3,0X1 
UP 
	MUL R5,R3,R0
	BL DIV 
	CMP R5,#0
	BEQ EXIT 
	ADD R3,#1
	B UP 
EXIT MUL R4,R3,R0 
	STR R4,[R2]
STOP 
	B STOP 
DIV SUBHS R5,R1
	CMP R5,R1
	BHS DIV 
	BX LR 
SRC1 DCD 0X3 
SRC2 DCD 0X4 
	AREA mydata,DATA,READWRITE 
RES DCD 0 
	END 